/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedMonitoringRouteImport } from './routes/_authed/monitoring'
import { Route as AuthedGuideRouteImport } from './routes/_authed/guide'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedAppsIndexRouteImport } from './routes/_authed/apps/index'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as AuthedSettingsRegistryRouteImport } from './routes/_authed/settings/registry'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed/settings/notifications'
import { Route as AuthedAppsIdRouteImport } from './routes/_authed/apps/$id'
import { Route as AuthedSettingsSecurityIndexRouteImport } from './routes/_authed/settings/security/index'
import { Route as AuthedSettingsGitProvidersIndexRouteImport } from './routes/_authed/settings/git-providers/index'
import { Route as AuthedAppsIdIndexRouteImport } from './routes/_authed/apps/$id/index'
import { Route as AuthedSettingsSecurityTotpRouteImport } from './routes/_authed/settings/security/totp'
import { Route as AuthedSettingsSecuritySessionsRouteImport } from './routes/_authed/settings/security/sessions'
import { Route as AuthedSettingsSecurityPostureRouteImport } from './routes/_authed/settings/security/posture'
import { Route as AuthedSettingsSecurityPasskeysRouteImport } from './routes/_authed/settings/security/passkeys'
import { Route as AuthedSettingsSecurityPasskeyRouteImport } from './routes/_authed/settings/security/passkey'
import { Route as AuthedSettingsGitProvidersSlugRouteImport } from './routes/_authed/settings/git-providers/$slug'
import { Route as AuthedAppsIdShellRouteImport } from './routes/_authed/apps/$id/shell'
import { Route as AuthedAppsIdSettingsRouteImport } from './routes/_authed/apps/$id/settings'
import { Route as AuthedAppsIdOverviewRouteImport } from './routes/_authed/apps/$id/overview'
import { Route as AuthedAppsIdLogsRouteImport } from './routes/_authed/apps/$id/logs'
import { Route as AuthedAppsIdEnvRouteImport } from './routes/_authed/apps/$id/env'
import { Route as AuthedAppsIdDomainsRouteImport } from './routes/_authed/apps/$id/domains'
import { Route as AuthedAppsIdDeploymentsRouteImport } from './routes/_authed/apps/$id/deployments'
import { Route as AuthedAppsIdSettingsIndexRouteImport } from './routes/_authed/apps/$id/settings/index'
import { Route as AuthedAppsIdSettingsWebhooksRouteImport } from './routes/_authed/apps/$id/settings/webhooks'
import { Route as AuthedAppsIdSettingsWebhookSecretRouteImport } from './routes/_authed/apps/$id/settings/webhook-secret'
import { Route as AuthedAppsIdSettingsNotificationsRouteImport } from './routes/_authed/apps/$id/settings/notifications'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedMonitoringRoute = AuthedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGuideRoute = AuthedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsIndexRoute = AuthedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRegistryRoute = AuthedSettingsRegistryRouteImport.update({
  id: '/settings/registry',
  path: '/settings/registry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAppsIdRoute = AuthedAppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSecurityIndexRoute =
  AuthedSettingsSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsGitProvidersIndexRoute =
  AuthedSettingsGitProvidersIndexRouteImport.update({
    id: '/settings/git-providers/',
    path: '/settings/git-providers/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAppsIdIndexRoute = AuthedAppsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedSettingsSecurityTotpRoute =
  AuthedSettingsSecurityTotpRouteImport.update({
    id: '/totp',
    path: '/totp',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecuritySessionsRoute =
  AuthedSettingsSecuritySessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPostureRoute =
  AuthedSettingsSecurityPostureRouteImport.update({
    id: '/posture',
    path: '/posture',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPasskeysRoute =
  AuthedSettingsSecurityPasskeysRouteImport.update({
    id: '/passkeys',
    path: '/passkeys',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPasskeyRoute =
  AuthedSettingsSecurityPasskeyRouteImport.update({
    id: '/passkey',
    path: '/passkey',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsGitProvidersSlugRoute =
  AuthedSettingsGitProvidersSlugRouteImport.update({
    id: '/settings/git-providers/$slug',
    path: '/settings/git-providers/$slug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAppsIdShellRoute = AuthedAppsIdShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdSettingsRoute = AuthedAppsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdOverviewRoute = AuthedAppsIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdLogsRoute = AuthedAppsIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdEnvRoute = AuthedAppsIdEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdDomainsRoute = AuthedAppsIdDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdDeploymentsRoute = AuthedAppsIdDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AuthedAppsIdRoute,
} as any)
const AuthedAppsIdSettingsIndexRoute =
  AuthedAppsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppsIdSettingsRoute,
  } as any)
const AuthedAppsIdSettingsWebhooksRoute =
  AuthedAppsIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthedAppsIdSettingsRoute,
  } as any)
const AuthedAppsIdSettingsWebhookSecretRoute =
  AuthedAppsIdSettingsWebhookSecretRouteImport.update({
    id: '/webhook-secret',
    path: '/webhook-secret',
    getParentRoute: () => AuthedAppsIdSettingsRoute,
  } as any)
const AuthedAppsIdSettingsNotificationsRoute =
  AuthedAppsIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedAppsIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/guide': typeof AuthedGuideRoute
  '/monitoring': typeof AuthedMonitoringRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/apps/$id': typeof AuthedAppsIdRouteWithChildren
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/registry': typeof AuthedSettingsRegistryRoute
  '/settings/security': typeof AuthedSettingsSecurityRouteWithChildren
  '/apps/': typeof AuthedAppsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/apps/$id/deployments': typeof AuthedAppsIdDeploymentsRoute
  '/apps/$id/domains': typeof AuthedAppsIdDomainsRoute
  '/apps/$id/env': typeof AuthedAppsIdEnvRoute
  '/apps/$id/logs': typeof AuthedAppsIdLogsRoute
  '/apps/$id/overview': typeof AuthedAppsIdOverviewRoute
  '/apps/$id/settings': typeof AuthedAppsIdSettingsRouteWithChildren
  '/apps/$id/shell': typeof AuthedAppsIdShellRoute
  '/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/apps/$id/': typeof AuthedAppsIdIndexRoute
  '/settings/git-providers/': typeof AuthedSettingsGitProvidersIndexRoute
  '/settings/security/': typeof AuthedSettingsSecurityIndexRoute
  '/apps/$id/settings/notifications': typeof AuthedAppsIdSettingsNotificationsRoute
  '/apps/$id/settings/webhook-secret': typeof AuthedAppsIdSettingsWebhookSecretRoute
  '/apps/$id/settings/webhooks': typeof AuthedAppsIdSettingsWebhooksRoute
  '/apps/$id/settings/': typeof AuthedAppsIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/guide': typeof AuthedGuideRoute
  '/monitoring': typeof AuthedMonitoringRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/registry': typeof AuthedSettingsRegistryRoute
  '/apps': typeof AuthedAppsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/apps/$id/deployments': typeof AuthedAppsIdDeploymentsRoute
  '/apps/$id/domains': typeof AuthedAppsIdDomainsRoute
  '/apps/$id/env': typeof AuthedAppsIdEnvRoute
  '/apps/$id/logs': typeof AuthedAppsIdLogsRoute
  '/apps/$id/overview': typeof AuthedAppsIdOverviewRoute
  '/apps/$id/shell': typeof AuthedAppsIdShellRoute
  '/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/apps/$id': typeof AuthedAppsIdIndexRoute
  '/settings/git-providers': typeof AuthedSettingsGitProvidersIndexRoute
  '/settings/security': typeof AuthedSettingsSecurityIndexRoute
  '/apps/$id/settings/notifications': typeof AuthedAppsIdSettingsNotificationsRoute
  '/apps/$id/settings/webhook-secret': typeof AuthedAppsIdSettingsWebhookSecretRoute
  '/apps/$id/settings/webhooks': typeof AuthedAppsIdSettingsWebhooksRoute
  '/apps/$id/settings': typeof AuthedAppsIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/guide': typeof AuthedGuideRoute
  '/_authed/monitoring': typeof AuthedMonitoringRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/apps/$id': typeof AuthedAppsIdRouteWithChildren
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/registry': typeof AuthedSettingsRegistryRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRouteWithChildren
  '/_authed/apps/': typeof AuthedAppsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/apps/$id/deployments': typeof AuthedAppsIdDeploymentsRoute
  '/_authed/apps/$id/domains': typeof AuthedAppsIdDomainsRoute
  '/_authed/apps/$id/env': typeof AuthedAppsIdEnvRoute
  '/_authed/apps/$id/logs': typeof AuthedAppsIdLogsRoute
  '/_authed/apps/$id/overview': typeof AuthedAppsIdOverviewRoute
  '/_authed/apps/$id/settings': typeof AuthedAppsIdSettingsRouteWithChildren
  '/_authed/apps/$id/shell': typeof AuthedAppsIdShellRoute
  '/_authed/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/_authed/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/_authed/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/_authed/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/_authed/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/_authed/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/_authed/apps/$id/': typeof AuthedAppsIdIndexRoute
  '/_authed/settings/git-providers/': typeof AuthedSettingsGitProvidersIndexRoute
  '/_authed/settings/security/': typeof AuthedSettingsSecurityIndexRoute
  '/_authed/apps/$id/settings/notifications': typeof AuthedAppsIdSettingsNotificationsRoute
  '/_authed/apps/$id/settings/webhook-secret': typeof AuthedAppsIdSettingsWebhookSecretRoute
  '/_authed/apps/$id/settings/webhooks': typeof AuthedAppsIdSettingsWebhooksRoute
  '/_authed/apps/$id/settings/': typeof AuthedAppsIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/monitoring'
    | '/login'
    | '/register'
    | '/apps/$id'
    | '/settings/notifications'
    | '/settings/registry'
    | '/settings/security'
    | '/apps/'
    | '/settings/'
    | '/apps/$id/deployments'
    | '/apps/$id/domains'
    | '/apps/$id/env'
    | '/apps/$id/logs'
    | '/apps/$id/overview'
    | '/apps/$id/settings'
    | '/apps/$id/shell'
    | '/settings/git-providers/$slug'
    | '/settings/security/passkey'
    | '/settings/security/passkeys'
    | '/settings/security/posture'
    | '/settings/security/sessions'
    | '/settings/security/totp'
    | '/apps/$id/'
    | '/settings/git-providers/'
    | '/settings/security/'
    | '/apps/$id/settings/notifications'
    | '/apps/$id/settings/webhook-secret'
    | '/apps/$id/settings/webhooks'
    | '/apps/$id/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/monitoring'
    | '/login'
    | '/register'
    | '/settings/notifications'
    | '/settings/registry'
    | '/apps'
    | '/settings'
    | '/apps/$id/deployments'
    | '/apps/$id/domains'
    | '/apps/$id/env'
    | '/apps/$id/logs'
    | '/apps/$id/overview'
    | '/apps/$id/shell'
    | '/settings/git-providers/$slug'
    | '/settings/security/passkey'
    | '/settings/security/passkeys'
    | '/settings/security/posture'
    | '/settings/security/sessions'
    | '/settings/security/totp'
    | '/apps/$id'
    | '/settings/git-providers'
    | '/settings/security'
    | '/apps/$id/settings/notifications'
    | '/apps/$id/settings/webhook-secret'
    | '/apps/$id/settings/webhooks'
    | '/apps/$id/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/dashboard'
    | '/_authed/guide'
    | '/_authed/monitoring'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_authed/apps/$id'
    | '/_authed/settings/notifications'
    | '/_authed/settings/registry'
    | '/_authed/settings/security'
    | '/_authed/apps/'
    | '/_authed/settings/'
    | '/_authed/apps/$id/deployments'
    | '/_authed/apps/$id/domains'
    | '/_authed/apps/$id/env'
    | '/_authed/apps/$id/logs'
    | '/_authed/apps/$id/overview'
    | '/_authed/apps/$id/settings'
    | '/_authed/apps/$id/shell'
    | '/_authed/settings/git-providers/$slug'
    | '/_authed/settings/security/passkey'
    | '/_authed/settings/security/passkeys'
    | '/_authed/settings/security/posture'
    | '/_authed/settings/security/sessions'
    | '/_authed/settings/security/totp'
    | '/_authed/apps/$id/'
    | '/_authed/settings/git-providers/'
    | '/_authed/settings/security/'
    | '/_authed/apps/$id/settings/notifications'
    | '/_authed/apps/$id/settings/webhook-secret'
    | '/_authed/apps/$id/settings/webhooks'
    | '/_authed/apps/$id/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/monitoring': {
      id: '/_authed/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthedMonitoringRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/guide': {
      id: '/_authed/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthedGuideRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/': {
      id: '/_authed/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthedAppsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/registry': {
      id: '/_authed/settings/registry'
      path: '/settings/registry'
      fullPath: '/settings/registry'
      preLoaderRoute: typeof AuthedSettingsRegistryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$id': {
      id: '/_authed/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AuthedAppsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/security/': {
      id: '/_authed/settings/security/'
      path: '/'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthedSettingsSecurityIndexRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/git-providers/': {
      id: '/_authed/settings/git-providers/'
      path: '/settings/git-providers'
      fullPath: '/settings/git-providers/'
      preLoaderRoute: typeof AuthedSettingsGitProvidersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$id/': {
      id: '/_authed/apps/$id/'
      path: '/'
      fullPath: '/apps/$id/'
      preLoaderRoute: typeof AuthedAppsIdIndexRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/settings/security/totp': {
      id: '/_authed/settings/security/totp'
      path: '/totp'
      fullPath: '/settings/security/totp'
      preLoaderRoute: typeof AuthedSettingsSecurityTotpRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/sessions': {
      id: '/_authed/settings/security/sessions'
      path: '/sessions'
      fullPath: '/settings/security/sessions'
      preLoaderRoute: typeof AuthedSettingsSecuritySessionsRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/posture': {
      id: '/_authed/settings/security/posture'
      path: '/posture'
      fullPath: '/settings/security/posture'
      preLoaderRoute: typeof AuthedSettingsSecurityPostureRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/passkeys': {
      id: '/_authed/settings/security/passkeys'
      path: '/passkeys'
      fullPath: '/settings/security/passkeys'
      preLoaderRoute: typeof AuthedSettingsSecurityPasskeysRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/passkey': {
      id: '/_authed/settings/security/passkey'
      path: '/passkey'
      fullPath: '/settings/security/passkey'
      preLoaderRoute: typeof AuthedSettingsSecurityPasskeyRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/git-providers/$slug': {
      id: '/_authed/settings/git-providers/$slug'
      path: '/settings/git-providers/$slug'
      fullPath: '/settings/git-providers/$slug'
      preLoaderRoute: typeof AuthedSettingsGitProvidersSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$id/shell': {
      id: '/_authed/apps/$id/shell'
      path: '/shell'
      fullPath: '/apps/$id/shell'
      preLoaderRoute: typeof AuthedAppsIdShellRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/settings': {
      id: '/_authed/apps/$id/settings'
      path: '/settings'
      fullPath: '/apps/$id/settings'
      preLoaderRoute: typeof AuthedAppsIdSettingsRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/overview': {
      id: '/_authed/apps/$id/overview'
      path: '/overview'
      fullPath: '/apps/$id/overview'
      preLoaderRoute: typeof AuthedAppsIdOverviewRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/logs': {
      id: '/_authed/apps/$id/logs'
      path: '/logs'
      fullPath: '/apps/$id/logs'
      preLoaderRoute: typeof AuthedAppsIdLogsRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/env': {
      id: '/_authed/apps/$id/env'
      path: '/env'
      fullPath: '/apps/$id/env'
      preLoaderRoute: typeof AuthedAppsIdEnvRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/domains': {
      id: '/_authed/apps/$id/domains'
      path: '/domains'
      fullPath: '/apps/$id/domains'
      preLoaderRoute: typeof AuthedAppsIdDomainsRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/deployments': {
      id: '/_authed/apps/$id/deployments'
      path: '/deployments'
      fullPath: '/apps/$id/deployments'
      preLoaderRoute: typeof AuthedAppsIdDeploymentsRouteImport
      parentRoute: typeof AuthedAppsIdRoute
    }
    '/_authed/apps/$id/settings/': {
      id: '/_authed/apps/$id/settings/'
      path: '/'
      fullPath: '/apps/$id/settings/'
      preLoaderRoute: typeof AuthedAppsIdSettingsIndexRouteImport
      parentRoute: typeof AuthedAppsIdSettingsRoute
    }
    '/_authed/apps/$id/settings/webhooks': {
      id: '/_authed/apps/$id/settings/webhooks'
      path: '/webhooks'
      fullPath: '/apps/$id/settings/webhooks'
      preLoaderRoute: typeof AuthedAppsIdSettingsWebhooksRouteImport
      parentRoute: typeof AuthedAppsIdSettingsRoute
    }
    '/_authed/apps/$id/settings/webhook-secret': {
      id: '/_authed/apps/$id/settings/webhook-secret'
      path: '/webhook-secret'
      fullPath: '/apps/$id/settings/webhook-secret'
      preLoaderRoute: typeof AuthedAppsIdSettingsWebhookSecretRouteImport
      parentRoute: typeof AuthedAppsIdSettingsRoute
    }
    '/_authed/apps/$id/settings/notifications': {
      id: '/_authed/apps/$id/settings/notifications'
      path: '/notifications'
      fullPath: '/apps/$id/settings/notifications'
      preLoaderRoute: typeof AuthedAppsIdSettingsNotificationsRouteImport
      parentRoute: typeof AuthedAppsIdSettingsRoute
    }
  }
}

interface AuthedAppsIdSettingsRouteChildren {
  AuthedAppsIdSettingsNotificationsRoute: typeof AuthedAppsIdSettingsNotificationsRoute
  AuthedAppsIdSettingsWebhookSecretRoute: typeof AuthedAppsIdSettingsWebhookSecretRoute
  AuthedAppsIdSettingsWebhooksRoute: typeof AuthedAppsIdSettingsWebhooksRoute
  AuthedAppsIdSettingsIndexRoute: typeof AuthedAppsIdSettingsIndexRoute
}

const AuthedAppsIdSettingsRouteChildren: AuthedAppsIdSettingsRouteChildren = {
  AuthedAppsIdSettingsNotificationsRoute:
    AuthedAppsIdSettingsNotificationsRoute,
  AuthedAppsIdSettingsWebhookSecretRoute:
    AuthedAppsIdSettingsWebhookSecretRoute,
  AuthedAppsIdSettingsWebhooksRoute: AuthedAppsIdSettingsWebhooksRoute,
  AuthedAppsIdSettingsIndexRoute: AuthedAppsIdSettingsIndexRoute,
}

const AuthedAppsIdSettingsRouteWithChildren =
  AuthedAppsIdSettingsRoute._addFileChildren(AuthedAppsIdSettingsRouteChildren)

interface AuthedAppsIdRouteChildren {
  AuthedAppsIdDeploymentsRoute: typeof AuthedAppsIdDeploymentsRoute
  AuthedAppsIdDomainsRoute: typeof AuthedAppsIdDomainsRoute
  AuthedAppsIdEnvRoute: typeof AuthedAppsIdEnvRoute
  AuthedAppsIdLogsRoute: typeof AuthedAppsIdLogsRoute
  AuthedAppsIdOverviewRoute: typeof AuthedAppsIdOverviewRoute
  AuthedAppsIdSettingsRoute: typeof AuthedAppsIdSettingsRouteWithChildren
  AuthedAppsIdShellRoute: typeof AuthedAppsIdShellRoute
  AuthedAppsIdIndexRoute: typeof AuthedAppsIdIndexRoute
}

const AuthedAppsIdRouteChildren: AuthedAppsIdRouteChildren = {
  AuthedAppsIdDeploymentsRoute: AuthedAppsIdDeploymentsRoute,
  AuthedAppsIdDomainsRoute: AuthedAppsIdDomainsRoute,
  AuthedAppsIdEnvRoute: AuthedAppsIdEnvRoute,
  AuthedAppsIdLogsRoute: AuthedAppsIdLogsRoute,
  AuthedAppsIdOverviewRoute: AuthedAppsIdOverviewRoute,
  AuthedAppsIdSettingsRoute: AuthedAppsIdSettingsRouteWithChildren,
  AuthedAppsIdShellRoute: AuthedAppsIdShellRoute,
  AuthedAppsIdIndexRoute: AuthedAppsIdIndexRoute,
}

const AuthedAppsIdRouteWithChildren = AuthedAppsIdRoute._addFileChildren(
  AuthedAppsIdRouteChildren,
)

interface AuthedSettingsSecurityRouteChildren {
  AuthedSettingsSecurityPasskeyRoute: typeof AuthedSettingsSecurityPasskeyRoute
  AuthedSettingsSecurityPasskeysRoute: typeof AuthedSettingsSecurityPasskeysRoute
  AuthedSettingsSecurityPostureRoute: typeof AuthedSettingsSecurityPostureRoute
  AuthedSettingsSecuritySessionsRoute: typeof AuthedSettingsSecuritySessionsRoute
  AuthedSettingsSecurityTotpRoute: typeof AuthedSettingsSecurityTotpRoute
  AuthedSettingsSecurityIndexRoute: typeof AuthedSettingsSecurityIndexRoute
}

const AuthedSettingsSecurityRouteChildren: AuthedSettingsSecurityRouteChildren =
  {
    AuthedSettingsSecurityPasskeyRoute: AuthedSettingsSecurityPasskeyRoute,
    AuthedSettingsSecurityPasskeysRoute: AuthedSettingsSecurityPasskeysRoute,
    AuthedSettingsSecurityPostureRoute: AuthedSettingsSecurityPostureRoute,
    AuthedSettingsSecuritySessionsRoute: AuthedSettingsSecuritySessionsRoute,
    AuthedSettingsSecurityTotpRoute: AuthedSettingsSecurityTotpRoute,
    AuthedSettingsSecurityIndexRoute: AuthedSettingsSecurityIndexRoute,
  }

const AuthedSettingsSecurityRouteWithChildren =
  AuthedSettingsSecurityRoute._addFileChildren(
    AuthedSettingsSecurityRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedGuideRoute: typeof AuthedGuideRoute
  AuthedMonitoringRoute: typeof AuthedMonitoringRoute
  AuthedAppsIdRoute: typeof AuthedAppsIdRouteWithChildren
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsRegistryRoute: typeof AuthedSettingsRegistryRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRouteWithChildren
  AuthedAppsIndexRoute: typeof AuthedAppsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsGitProvidersSlugRoute: typeof AuthedSettingsGitProvidersSlugRoute
  AuthedSettingsGitProvidersIndexRoute: typeof AuthedSettingsGitProvidersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedGuideRoute: AuthedGuideRoute,
  AuthedMonitoringRoute: AuthedMonitoringRoute,
  AuthedAppsIdRoute: AuthedAppsIdRouteWithChildren,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsRegistryRoute: AuthedSettingsRegistryRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRouteWithChildren,
  AuthedAppsIndexRoute: AuthedAppsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsGitProvidersSlugRoute: AuthedSettingsGitProvidersSlugRoute,
  AuthedSettingsGitProvidersIndexRoute: AuthedSettingsGitProvidersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
