/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedMonitoringRouteImport } from './routes/_authed/monitoring'
import { Route as AuthedGuideRouteImport } from './routes/_authed/guide'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as PublicInvitationsAcceptRouteImport } from './routes/_public/invitations/accept'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as AuthedSettingsRegistryRouteImport } from './routes/_authed/settings/registry'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed/settings/notifications'
import { Route as AuthedSettingsLicenseRouteImport } from './routes/_authed/settings/license'
import { Route as AuthedOrgsOrgSlugRouteImport } from './routes/_authed/orgs/$orgSlug'
import { Route as AuthedDatabasesSplatRouteImport } from './routes/_authed/databases.$'
import { Route as AuthedAppsSplatRouteImport } from './routes/_authed/apps.$'
import { Route as AuthedSettingsSecurityIndexRouteImport } from './routes/_authed/settings/security/index'
import { Route as AuthedSettingsGitProvidersIndexRouteImport } from './routes/_authed/settings/git-providers/index'
import { Route as AuthedOrgsOrgSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/index'
import { Route as AuthedSettingsSecurityTotpRouteImport } from './routes/_authed/settings/security/totp'
import { Route as AuthedSettingsSecuritySessionsRouteImport } from './routes/_authed/settings/security/sessions'
import { Route as AuthedSettingsSecurityPostureRouteImport } from './routes/_authed/settings/security/posture'
import { Route as AuthedSettingsSecurityPasskeysRouteImport } from './routes/_authed/settings/security/passkeys'
import { Route as AuthedSettingsSecurityPasskeyRouteImport } from './routes/_authed/settings/security/passkey'
import { Route as AuthedSettingsGitProvidersSlugRouteImport } from './routes/_authed/settings/git-providers/$slug'
import { Route as AuthedOrgsOrgSlugSettingsRouteImport } from './routes/_authed/orgs/$orgSlug/settings'
import { Route as AuthedOrgsOrgSlugMembersRouteImport } from './routes/_authed/orgs/$orgSlug/members'
import { Route as AuthedOrgsOrgSlugMarketplaceRouteImport } from './routes/_authed/orgs/$orgSlug/marketplace'
import { Route as AuthedOrgsOrgSlugDashboardRouteImport } from './routes/_authed/orgs/$orgSlug/dashboard'
import { Route as AuthedOrgsOrgSlugBrandingRouteImport } from './routes/_authed/orgs/$orgSlug/branding'
import { Route as AuthedOrgsOrgSlugAuditRouteImport } from './routes/_authed/orgs/$orgSlug/audit'
import { Route as AuthedOrgsOrgSlugSettingsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/settings/index'
import { Route as AuthedOrgsOrgSlugServicesIndexRouteImport } from './routes/_authed/orgs/$orgSlug/services/index'
import { Route as AuthedOrgsOrgSlugDatabasesIndexRouteImport } from './routes/_authed/orgs/$orgSlug/databases/index'
import { Route as AuthedOrgsOrgSlugAppsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/apps/index'
import { Route as AuthedOrgsOrgSlugSettingsSsoRouteImport } from './routes/_authed/orgs/$orgSlug/settings/sso'
import { Route as AuthedOrgsOrgSlugSettingsBillingRouteImport } from './routes/_authed/orgs/$orgSlug/settings/billing'
import { Route as AuthedOrgsOrgSlugServicesIdRouteImport } from './routes/_authed/orgs/$orgSlug/services/$id'
import { Route as AuthedOrgsOrgSlugDatabasesIdRouteImport } from './routes/_authed/orgs/$orgSlug/databases/$id'
import { Route as AuthedOrgsOrgSlugAppsIdRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id'
import { Route as AuthedOrgsOrgSlugAppsIdIndexRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/index'
import { Route as AuthedOrgsOrgSlugAppsIdShellRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/shell'
import { Route as AuthedOrgsOrgSlugAppsIdSettingsRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/settings'
import { Route as AuthedOrgsOrgSlugAppsIdOverviewRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/overview'
import { Route as AuthedOrgsOrgSlugAppsIdLogsRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/logs'
import { Route as AuthedOrgsOrgSlugAppsIdEnvRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/env'
import { Route as AuthedOrgsOrgSlugAppsIdDomainsRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/domains'
import { Route as AuthedOrgsOrgSlugAppsIdDeploymentsRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/deployments'
import { Route as AuthedOrgsOrgSlugAppsIdSettingsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/settings/index'
import { Route as AuthedOrgsOrgSlugAppsIdSettingsWebhooksRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/settings/webhooks'
import { Route as AuthedOrgsOrgSlugAppsIdSettingsProtectionRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/settings/protection'
import { Route as AuthedOrgsOrgSlugAppsIdSettingsAdvancedRouteImport } from './routes/_authed/orgs/$orgSlug/apps/$id/settings/advanced'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedMonitoringRoute = AuthedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGuideRoute = AuthedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const PublicInvitationsAcceptRoute = PublicInvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRegistryRoute = AuthedSettingsRegistryRouteImport.update({
  id: '/settings/registry',
  path: '/settings/registry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsLicenseRoute = AuthedSettingsLicenseRouteImport.update({
  id: '/settings/license',
  path: '/settings/license',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgsOrgSlugRoute = AuthedOrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabasesSplatRoute = AuthedDatabasesSplatRouteImport.update({
  id: '/databases/$',
  path: '/databases/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsSplatRoute = AuthedAppsSplatRouteImport.update({
  id: '/apps/$',
  path: '/apps/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSecurityIndexRoute =
  AuthedSettingsSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsGitProvidersIndexRoute =
  AuthedSettingsGitProvidersIndexRouteImport.update({
    id: '/settings/git-providers/',
    path: '/settings/git-providers/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgsOrgSlugIndexRoute = AuthedOrgsOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgSlugRoute,
} as any)
const AuthedSettingsSecurityTotpRoute =
  AuthedSettingsSecurityTotpRouteImport.update({
    id: '/totp',
    path: '/totp',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecuritySessionsRoute =
  AuthedSettingsSecuritySessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPostureRoute =
  AuthedSettingsSecurityPostureRouteImport.update({
    id: '/posture',
    path: '/posture',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPasskeysRoute =
  AuthedSettingsSecurityPasskeysRouteImport.update({
    id: '/passkeys',
    path: '/passkeys',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsSecurityPasskeyRoute =
  AuthedSettingsSecurityPasskeyRouteImport.update({
    id: '/passkey',
    path: '/passkey',
    getParentRoute: () => AuthedSettingsSecurityRoute,
  } as any)
const AuthedSettingsGitProvidersSlugRoute =
  AuthedSettingsGitProvidersSlugRouteImport.update({
    id: '/settings/git-providers/$slug',
    path: '/settings/git-providers/$slug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsRoute =
  AuthedOrgsOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugMembersRoute =
  AuthedOrgsOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugMarketplaceRoute =
  AuthedOrgsOrgSlugMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugDashboardRoute =
  AuthedOrgsOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugBrandingRoute =
  AuthedOrgsOrgSlugBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugAuditRoute = AuthedOrgsOrgSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedOrgsOrgSlugRoute,
} as any)
const AuthedOrgsOrgSlugSettingsIndexRoute =
  AuthedOrgsOrgSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugServicesIndexRoute =
  AuthedOrgsOrgSlugServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugDatabasesIndexRoute =
  AuthedOrgsOrgSlugDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIndexRoute =
  AuthedOrgsOrgSlugAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsSsoRoute =
  AuthedOrgsOrgSlugSettingsSsoRouteImport.update({
    id: '/sso',
    path: '/sso',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsBillingRoute =
  AuthedOrgsOrgSlugSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugServicesIdRoute =
  AuthedOrgsOrgSlugServicesIdRouteImport.update({
    id: '/services/$id',
    path: '/services/$id',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugDatabasesIdRoute =
  AuthedOrgsOrgSlugDatabasesIdRouteImport.update({
    id: '/databases/$id',
    path: '/databases/$id',
    getParentRoute: () => AuthedOrgsOrgSlugRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdRoute = AuthedOrgsOrgSlugAppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => AuthedOrgsOrgSlugRoute,
} as any)
const AuthedOrgsOrgSlugAppsIdIndexRoute =
  AuthedOrgsOrgSlugAppsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdShellRoute =
  AuthedOrgsOrgSlugAppsIdShellRouteImport.update({
    id: '/shell',
    path: '/shell',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdSettingsRoute =
  AuthedOrgsOrgSlugAppsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdOverviewRoute =
  AuthedOrgsOrgSlugAppsIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdLogsRoute =
  AuthedOrgsOrgSlugAppsIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdEnvRoute =
  AuthedOrgsOrgSlugAppsIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdDomainsRoute =
  AuthedOrgsOrgSlugAppsIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdDeploymentsRoute =
  AuthedOrgsOrgSlugAppsIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdSettingsIndexRoute =
  AuthedOrgsOrgSlugAppsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute =
  AuthedOrgsOrgSlugAppsIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute =
  AuthedOrgsOrgSlugAppsIdSettingsProtectionRouteImport.update({
    id: '/protection',
    path: '/protection',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdSettingsRoute,
  } as any)
const AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute =
  AuthedOrgsOrgSlugAppsIdSettingsAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => AuthedOrgsOrgSlugAppsIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/guide': typeof AuthedGuideRoute
  '/monitoring': typeof AuthedMonitoringRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/apps/$': typeof AuthedAppsSplatRoute
  '/databases/$': typeof AuthedDatabasesSplatRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteWithChildren
  '/settings/license': typeof AuthedSettingsLicenseRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/registry': typeof AuthedSettingsRegistryRoute
  '/settings/security': typeof AuthedSettingsSecurityRouteWithChildren
  '/invitations/accept': typeof PublicInvitationsAcceptRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/orgs/$orgSlug/audit': typeof AuthedOrgsOrgSlugAuditRoute
  '/orgs/$orgSlug/branding': typeof AuthedOrgsOrgSlugBrandingRoute
  '/orgs/$orgSlug/dashboard': typeof AuthedOrgsOrgSlugDashboardRoute
  '/orgs/$orgSlug/marketplace': typeof AuthedOrgsOrgSlugMarketplaceRoute
  '/orgs/$orgSlug/members': typeof AuthedOrgsOrgSlugMembersRoute
  '/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsRouteWithChildren
  '/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/settings/git-providers/': typeof AuthedSettingsGitProvidersIndexRoute
  '/settings/security/': typeof AuthedSettingsSecurityIndexRoute
  '/orgs/$orgSlug/apps/$id': typeof AuthedOrgsOrgSlugAppsIdRouteWithChildren
  '/orgs/$orgSlug/databases/$id': typeof AuthedOrgsOrgSlugDatabasesIdRoute
  '/orgs/$orgSlug/services/$id': typeof AuthedOrgsOrgSlugServicesIdRoute
  '/orgs/$orgSlug/settings/billing': typeof AuthedOrgsOrgSlugSettingsBillingRoute
  '/orgs/$orgSlug/settings/sso': typeof AuthedOrgsOrgSlugSettingsSsoRoute
  '/orgs/$orgSlug/apps/': typeof AuthedOrgsOrgSlugAppsIndexRoute
  '/orgs/$orgSlug/databases/': typeof AuthedOrgsOrgSlugDatabasesIndexRoute
  '/orgs/$orgSlug/services/': typeof AuthedOrgsOrgSlugServicesIndexRoute
  '/orgs/$orgSlug/settings/': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/orgs/$orgSlug/apps/$id/deployments': typeof AuthedOrgsOrgSlugAppsIdDeploymentsRoute
  '/orgs/$orgSlug/apps/$id/domains': typeof AuthedOrgsOrgSlugAppsIdDomainsRoute
  '/orgs/$orgSlug/apps/$id/env': typeof AuthedOrgsOrgSlugAppsIdEnvRoute
  '/orgs/$orgSlug/apps/$id/logs': typeof AuthedOrgsOrgSlugAppsIdLogsRoute
  '/orgs/$orgSlug/apps/$id/overview': typeof AuthedOrgsOrgSlugAppsIdOverviewRoute
  '/orgs/$orgSlug/apps/$id/settings': typeof AuthedOrgsOrgSlugAppsIdSettingsRouteWithChildren
  '/orgs/$orgSlug/apps/$id/shell': typeof AuthedOrgsOrgSlugAppsIdShellRoute
  '/orgs/$orgSlug/apps/$id/': typeof AuthedOrgsOrgSlugAppsIdIndexRoute
  '/orgs/$orgSlug/apps/$id/settings/advanced': typeof AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute
  '/orgs/$orgSlug/apps/$id/settings/protection': typeof AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute
  '/orgs/$orgSlug/apps/$id/settings/webhooks': typeof AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute
  '/orgs/$orgSlug/apps/$id/settings/': typeof AuthedOrgsOrgSlugAppsIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/guide': typeof AuthedGuideRoute
  '/monitoring': typeof AuthedMonitoringRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/apps/$': typeof AuthedAppsSplatRoute
  '/databases/$': typeof AuthedDatabasesSplatRoute
  '/settings/license': typeof AuthedSettingsLicenseRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/registry': typeof AuthedSettingsRegistryRoute
  '/invitations/accept': typeof PublicInvitationsAcceptRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/orgs/$orgSlug/audit': typeof AuthedOrgsOrgSlugAuditRoute
  '/orgs/$orgSlug/branding': typeof AuthedOrgsOrgSlugBrandingRoute
  '/orgs/$orgSlug/dashboard': typeof AuthedOrgsOrgSlugDashboardRoute
  '/orgs/$orgSlug/marketplace': typeof AuthedOrgsOrgSlugMarketplaceRoute
  '/orgs/$orgSlug/members': typeof AuthedOrgsOrgSlugMembersRoute
  '/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugIndexRoute
  '/settings/git-providers': typeof AuthedSettingsGitProvidersIndexRoute
  '/settings/security': typeof AuthedSettingsSecurityIndexRoute
  '/orgs/$orgSlug/databases/$id': typeof AuthedOrgsOrgSlugDatabasesIdRoute
  '/orgs/$orgSlug/services/$id': typeof AuthedOrgsOrgSlugServicesIdRoute
  '/orgs/$orgSlug/settings/billing': typeof AuthedOrgsOrgSlugSettingsBillingRoute
  '/orgs/$orgSlug/settings/sso': typeof AuthedOrgsOrgSlugSettingsSsoRoute
  '/orgs/$orgSlug/apps': typeof AuthedOrgsOrgSlugAppsIndexRoute
  '/orgs/$orgSlug/databases': typeof AuthedOrgsOrgSlugDatabasesIndexRoute
  '/orgs/$orgSlug/services': typeof AuthedOrgsOrgSlugServicesIndexRoute
  '/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/orgs/$orgSlug/apps/$id/deployments': typeof AuthedOrgsOrgSlugAppsIdDeploymentsRoute
  '/orgs/$orgSlug/apps/$id/domains': typeof AuthedOrgsOrgSlugAppsIdDomainsRoute
  '/orgs/$orgSlug/apps/$id/env': typeof AuthedOrgsOrgSlugAppsIdEnvRoute
  '/orgs/$orgSlug/apps/$id/logs': typeof AuthedOrgsOrgSlugAppsIdLogsRoute
  '/orgs/$orgSlug/apps/$id/overview': typeof AuthedOrgsOrgSlugAppsIdOverviewRoute
  '/orgs/$orgSlug/apps/$id/shell': typeof AuthedOrgsOrgSlugAppsIdShellRoute
  '/orgs/$orgSlug/apps/$id': typeof AuthedOrgsOrgSlugAppsIdIndexRoute
  '/orgs/$orgSlug/apps/$id/settings/advanced': typeof AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute
  '/orgs/$orgSlug/apps/$id/settings/protection': typeof AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute
  '/orgs/$orgSlug/apps/$id/settings/webhooks': typeof AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute
  '/orgs/$orgSlug/apps/$id/settings': typeof AuthedOrgsOrgSlugAppsIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/guide': typeof AuthedGuideRoute
  '/_authed/monitoring': typeof AuthedMonitoringRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/apps/$': typeof AuthedAppsSplatRoute
  '/_authed/databases/$': typeof AuthedDatabasesSplatRoute
  '/_authed/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteWithChildren
  '/_authed/settings/license': typeof AuthedSettingsLicenseRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/registry': typeof AuthedSettingsRegistryRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRouteWithChildren
  '/_public/invitations/accept': typeof PublicInvitationsAcceptRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/orgs/$orgSlug/audit': typeof AuthedOrgsOrgSlugAuditRoute
  '/_authed/orgs/$orgSlug/branding': typeof AuthedOrgsOrgSlugBrandingRoute
  '/_authed/orgs/$orgSlug/dashboard': typeof AuthedOrgsOrgSlugDashboardRoute
  '/_authed/orgs/$orgSlug/marketplace': typeof AuthedOrgsOrgSlugMarketplaceRoute
  '/_authed/orgs/$orgSlug/members': typeof AuthedOrgsOrgSlugMembersRoute
  '/_authed/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsRouteWithChildren
  '/_authed/settings/git-providers/$slug': typeof AuthedSettingsGitProvidersSlugRoute
  '/_authed/settings/security/passkey': typeof AuthedSettingsSecurityPasskeyRoute
  '/_authed/settings/security/passkeys': typeof AuthedSettingsSecurityPasskeysRoute
  '/_authed/settings/security/posture': typeof AuthedSettingsSecurityPostureRoute
  '/_authed/settings/security/sessions': typeof AuthedSettingsSecuritySessionsRoute
  '/_authed/settings/security/totp': typeof AuthedSettingsSecurityTotpRoute
  '/_authed/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/_authed/settings/git-providers/': typeof AuthedSettingsGitProvidersIndexRoute
  '/_authed/settings/security/': typeof AuthedSettingsSecurityIndexRoute
  '/_authed/orgs/$orgSlug/apps/$id': typeof AuthedOrgsOrgSlugAppsIdRouteWithChildren
  '/_authed/orgs/$orgSlug/databases/$id': typeof AuthedOrgsOrgSlugDatabasesIdRoute
  '/_authed/orgs/$orgSlug/services/$id': typeof AuthedOrgsOrgSlugServicesIdRoute
  '/_authed/orgs/$orgSlug/settings/billing': typeof AuthedOrgsOrgSlugSettingsBillingRoute
  '/_authed/orgs/$orgSlug/settings/sso': typeof AuthedOrgsOrgSlugSettingsSsoRoute
  '/_authed/orgs/$orgSlug/apps/': typeof AuthedOrgsOrgSlugAppsIndexRoute
  '/_authed/orgs/$orgSlug/databases/': typeof AuthedOrgsOrgSlugDatabasesIndexRoute
  '/_authed/orgs/$orgSlug/services/': typeof AuthedOrgsOrgSlugServicesIndexRoute
  '/_authed/orgs/$orgSlug/settings/': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/_authed/orgs/$orgSlug/apps/$id/deployments': typeof AuthedOrgsOrgSlugAppsIdDeploymentsRoute
  '/_authed/orgs/$orgSlug/apps/$id/domains': typeof AuthedOrgsOrgSlugAppsIdDomainsRoute
  '/_authed/orgs/$orgSlug/apps/$id/env': typeof AuthedOrgsOrgSlugAppsIdEnvRoute
  '/_authed/orgs/$orgSlug/apps/$id/logs': typeof AuthedOrgsOrgSlugAppsIdLogsRoute
  '/_authed/orgs/$orgSlug/apps/$id/overview': typeof AuthedOrgsOrgSlugAppsIdOverviewRoute
  '/_authed/orgs/$orgSlug/apps/$id/settings': typeof AuthedOrgsOrgSlugAppsIdSettingsRouteWithChildren
  '/_authed/orgs/$orgSlug/apps/$id/shell': typeof AuthedOrgsOrgSlugAppsIdShellRoute
  '/_authed/orgs/$orgSlug/apps/$id/': typeof AuthedOrgsOrgSlugAppsIdIndexRoute
  '/_authed/orgs/$orgSlug/apps/$id/settings/advanced': typeof AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute
  '/_authed/orgs/$orgSlug/apps/$id/settings/protection': typeof AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute
  '/_authed/orgs/$orgSlug/apps/$id/settings/webhooks': typeof AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute
  '/_authed/orgs/$orgSlug/apps/$id/settings/': typeof AuthedOrgsOrgSlugAppsIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/monitoring'
    | '/login'
    | '/register'
    | '/apps/$'
    | '/databases/$'
    | '/orgs/$orgSlug'
    | '/settings/license'
    | '/settings/notifications'
    | '/settings/registry'
    | '/settings/security'
    | '/invitations/accept'
    | '/settings/'
    | '/orgs/$orgSlug/audit'
    | '/orgs/$orgSlug/branding'
    | '/orgs/$orgSlug/dashboard'
    | '/orgs/$orgSlug/marketplace'
    | '/orgs/$orgSlug/members'
    | '/orgs/$orgSlug/settings'
    | '/settings/git-providers/$slug'
    | '/settings/security/passkey'
    | '/settings/security/passkeys'
    | '/settings/security/posture'
    | '/settings/security/sessions'
    | '/settings/security/totp'
    | '/orgs/$orgSlug/'
    | '/settings/git-providers/'
    | '/settings/security/'
    | '/orgs/$orgSlug/apps/$id'
    | '/orgs/$orgSlug/databases/$id'
    | '/orgs/$orgSlug/services/$id'
    | '/orgs/$orgSlug/settings/billing'
    | '/orgs/$orgSlug/settings/sso'
    | '/orgs/$orgSlug/apps/'
    | '/orgs/$orgSlug/databases/'
    | '/orgs/$orgSlug/services/'
    | '/orgs/$orgSlug/settings/'
    | '/orgs/$orgSlug/apps/$id/deployments'
    | '/orgs/$orgSlug/apps/$id/domains'
    | '/orgs/$orgSlug/apps/$id/env'
    | '/orgs/$orgSlug/apps/$id/logs'
    | '/orgs/$orgSlug/apps/$id/overview'
    | '/orgs/$orgSlug/apps/$id/settings'
    | '/orgs/$orgSlug/apps/$id/shell'
    | '/orgs/$orgSlug/apps/$id/'
    | '/orgs/$orgSlug/apps/$id/settings/advanced'
    | '/orgs/$orgSlug/apps/$id/settings/protection'
    | '/orgs/$orgSlug/apps/$id/settings/webhooks'
    | '/orgs/$orgSlug/apps/$id/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/monitoring'
    | '/login'
    | '/register'
    | '/apps/$'
    | '/databases/$'
    | '/settings/license'
    | '/settings/notifications'
    | '/settings/registry'
    | '/invitations/accept'
    | '/settings'
    | '/orgs/$orgSlug/audit'
    | '/orgs/$orgSlug/branding'
    | '/orgs/$orgSlug/dashboard'
    | '/orgs/$orgSlug/marketplace'
    | '/orgs/$orgSlug/members'
    | '/settings/git-providers/$slug'
    | '/settings/security/passkey'
    | '/settings/security/passkeys'
    | '/settings/security/posture'
    | '/settings/security/sessions'
    | '/settings/security/totp'
    | '/orgs/$orgSlug'
    | '/settings/git-providers'
    | '/settings/security'
    | '/orgs/$orgSlug/databases/$id'
    | '/orgs/$orgSlug/services/$id'
    | '/orgs/$orgSlug/settings/billing'
    | '/orgs/$orgSlug/settings/sso'
    | '/orgs/$orgSlug/apps'
    | '/orgs/$orgSlug/databases'
    | '/orgs/$orgSlug/services'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/apps/$id/deployments'
    | '/orgs/$orgSlug/apps/$id/domains'
    | '/orgs/$orgSlug/apps/$id/env'
    | '/orgs/$orgSlug/apps/$id/logs'
    | '/orgs/$orgSlug/apps/$id/overview'
    | '/orgs/$orgSlug/apps/$id/shell'
    | '/orgs/$orgSlug/apps/$id'
    | '/orgs/$orgSlug/apps/$id/settings/advanced'
    | '/orgs/$orgSlug/apps/$id/settings/protection'
    | '/orgs/$orgSlug/apps/$id/settings/webhooks'
    | '/orgs/$orgSlug/apps/$id/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/dashboard'
    | '/_authed/guide'
    | '/_authed/monitoring'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_authed/apps/$'
    | '/_authed/databases/$'
    | '/_authed/orgs/$orgSlug'
    | '/_authed/settings/license'
    | '/_authed/settings/notifications'
    | '/_authed/settings/registry'
    | '/_authed/settings/security'
    | '/_public/invitations/accept'
    | '/_authed/settings/'
    | '/_authed/orgs/$orgSlug/audit'
    | '/_authed/orgs/$orgSlug/branding'
    | '/_authed/orgs/$orgSlug/dashboard'
    | '/_authed/orgs/$orgSlug/marketplace'
    | '/_authed/orgs/$orgSlug/members'
    | '/_authed/orgs/$orgSlug/settings'
    | '/_authed/settings/git-providers/$slug'
    | '/_authed/settings/security/passkey'
    | '/_authed/settings/security/passkeys'
    | '/_authed/settings/security/posture'
    | '/_authed/settings/security/sessions'
    | '/_authed/settings/security/totp'
    | '/_authed/orgs/$orgSlug/'
    | '/_authed/settings/git-providers/'
    | '/_authed/settings/security/'
    | '/_authed/orgs/$orgSlug/apps/$id'
    | '/_authed/orgs/$orgSlug/databases/$id'
    | '/_authed/orgs/$orgSlug/services/$id'
    | '/_authed/orgs/$orgSlug/settings/billing'
    | '/_authed/orgs/$orgSlug/settings/sso'
    | '/_authed/orgs/$orgSlug/apps/'
    | '/_authed/orgs/$orgSlug/databases/'
    | '/_authed/orgs/$orgSlug/services/'
    | '/_authed/orgs/$orgSlug/settings/'
    | '/_authed/orgs/$orgSlug/apps/$id/deployments'
    | '/_authed/orgs/$orgSlug/apps/$id/domains'
    | '/_authed/orgs/$orgSlug/apps/$id/env'
    | '/_authed/orgs/$orgSlug/apps/$id/logs'
    | '/_authed/orgs/$orgSlug/apps/$id/overview'
    | '/_authed/orgs/$orgSlug/apps/$id/settings'
    | '/_authed/orgs/$orgSlug/apps/$id/shell'
    | '/_authed/orgs/$orgSlug/apps/$id/'
    | '/_authed/orgs/$orgSlug/apps/$id/settings/advanced'
    | '/_authed/orgs/$orgSlug/apps/$id/settings/protection'
    | '/_authed/orgs/$orgSlug/apps/$id/settings/webhooks'
    | '/_authed/orgs/$orgSlug/apps/$id/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/monitoring': {
      id: '/_authed/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthedMonitoringRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/guide': {
      id: '/_authed/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthedGuideRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_public/invitations/accept': {
      id: '/_public/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof PublicInvitationsAcceptRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/registry': {
      id: '/_authed/settings/registry'
      path: '/settings/registry'
      fullPath: '/settings/registry'
      preLoaderRoute: typeof AuthedSettingsRegistryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/license': {
      id: '/_authed/settings/license'
      path: '/settings/license'
      fullPath: '/settings/license'
      preLoaderRoute: typeof AuthedSettingsLicenseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orgs/$orgSlug': {
      id: '/_authed/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/databases/$': {
      id: '/_authed/databases/$'
      path: '/databases/$'
      fullPath: '/databases/$'
      preLoaderRoute: typeof AuthedDatabasesSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$': {
      id: '/_authed/apps/$'
      path: '/apps/$'
      fullPath: '/apps/$'
      preLoaderRoute: typeof AuthedAppsSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/security/': {
      id: '/_authed/settings/security/'
      path: '/'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthedSettingsSecurityIndexRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/git-providers/': {
      id: '/_authed/settings/git-providers/'
      path: '/settings/git-providers'
      fullPath: '/settings/git-providers/'
      preLoaderRoute: typeof AuthedSettingsGitProvidersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orgs/$orgSlug/': {
      id: '/_authed/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/settings/security/totp': {
      id: '/_authed/settings/security/totp'
      path: '/totp'
      fullPath: '/settings/security/totp'
      preLoaderRoute: typeof AuthedSettingsSecurityTotpRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/sessions': {
      id: '/_authed/settings/security/sessions'
      path: '/sessions'
      fullPath: '/settings/security/sessions'
      preLoaderRoute: typeof AuthedSettingsSecuritySessionsRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/posture': {
      id: '/_authed/settings/security/posture'
      path: '/posture'
      fullPath: '/settings/security/posture'
      preLoaderRoute: typeof AuthedSettingsSecurityPostureRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/passkeys': {
      id: '/_authed/settings/security/passkeys'
      path: '/passkeys'
      fullPath: '/settings/security/passkeys'
      preLoaderRoute: typeof AuthedSettingsSecurityPasskeysRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/security/passkey': {
      id: '/_authed/settings/security/passkey'
      path: '/passkey'
      fullPath: '/settings/security/passkey'
      preLoaderRoute: typeof AuthedSettingsSecurityPasskeyRouteImport
      parentRoute: typeof AuthedSettingsSecurityRoute
    }
    '/_authed/settings/git-providers/$slug': {
      id: '/_authed/settings/git-providers/$slug'
      path: '/settings/git-providers/$slug'
      fullPath: '/settings/git-providers/$slug'
      preLoaderRoute: typeof AuthedSettingsGitProvidersSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orgs/$orgSlug/settings': {
      id: '/_authed/orgs/$orgSlug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/members': {
      id: '/_authed/orgs/$orgSlug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/members'
      preLoaderRoute: typeof AuthedOrgsOrgSlugMembersRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/marketplace': {
      id: '/_authed/orgs/$orgSlug/marketplace'
      path: '/marketplace'
      fullPath: '/orgs/$orgSlug/marketplace'
      preLoaderRoute: typeof AuthedOrgsOrgSlugMarketplaceRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/dashboard': {
      id: '/_authed/orgs/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/orgs/$orgSlug/dashboard'
      preLoaderRoute: typeof AuthedOrgsOrgSlugDashboardRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/branding': {
      id: '/_authed/orgs/$orgSlug/branding'
      path: '/branding'
      fullPath: '/orgs/$orgSlug/branding'
      preLoaderRoute: typeof AuthedOrgsOrgSlugBrandingRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/audit': {
      id: '/_authed/orgs/$orgSlug/audit'
      path: '/audit'
      fullPath: '/orgs/$orgSlug/audit'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAuditRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/settings/': {
      id: '/_authed/orgs/$orgSlug/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRoute
    }
    '/_authed/orgs/$orgSlug/services/': {
      id: '/_authed/orgs/$orgSlug/services/'
      path: '/services'
      fullPath: '/orgs/$orgSlug/services/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugServicesIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/databases/': {
      id: '/_authed/orgs/$orgSlug/databases/'
      path: '/databases'
      fullPath: '/orgs/$orgSlug/databases/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugDatabasesIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/apps/': {
      id: '/_authed/orgs/$orgSlug/apps/'
      path: '/apps'
      fullPath: '/orgs/$orgSlug/apps/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/settings/sso': {
      id: '/_authed/orgs/$orgSlug/settings/sso'
      path: '/sso'
      fullPath: '/orgs/$orgSlug/settings/sso'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsSsoRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRoute
    }
    '/_authed/orgs/$orgSlug/settings/billing': {
      id: '/_authed/orgs/$orgSlug/settings/billing'
      path: '/billing'
      fullPath: '/orgs/$orgSlug/settings/billing'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsBillingRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRoute
    }
    '/_authed/orgs/$orgSlug/services/$id': {
      id: '/_authed/orgs/$orgSlug/services/$id'
      path: '/services/$id'
      fullPath: '/orgs/$orgSlug/services/$id'
      preLoaderRoute: typeof AuthedOrgsOrgSlugServicesIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/databases/$id': {
      id: '/_authed/orgs/$orgSlug/databases/$id'
      path: '/databases/$id'
      fullPath: '/orgs/$orgSlug/databases/$id'
      preLoaderRoute: typeof AuthedOrgsOrgSlugDatabasesIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id': {
      id: '/_authed/orgs/$orgSlug/apps/$id'
      path: '/apps/$id'
      fullPath: '/orgs/$orgSlug/apps/$id'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/': {
      id: '/_authed/orgs/$orgSlug/apps/$id/'
      path: '/'
      fullPath: '/orgs/$orgSlug/apps/$id/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/shell': {
      id: '/_authed/orgs/$orgSlug/apps/$id/shell'
      path: '/shell'
      fullPath: '/orgs/$orgSlug/apps/$id/shell'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdShellRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/settings': {
      id: '/_authed/orgs/$orgSlug/apps/$id/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/apps/$id/settings'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/overview': {
      id: '/_authed/orgs/$orgSlug/apps/$id/overview'
      path: '/overview'
      fullPath: '/orgs/$orgSlug/apps/$id/overview'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdOverviewRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/logs': {
      id: '/_authed/orgs/$orgSlug/apps/$id/logs'
      path: '/logs'
      fullPath: '/orgs/$orgSlug/apps/$id/logs'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdLogsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/env': {
      id: '/_authed/orgs/$orgSlug/apps/$id/env'
      path: '/env'
      fullPath: '/orgs/$orgSlug/apps/$id/env'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdEnvRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/domains': {
      id: '/_authed/orgs/$orgSlug/apps/$id/domains'
      path: '/domains'
      fullPath: '/orgs/$orgSlug/apps/$id/domains'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdDomainsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/deployments': {
      id: '/_authed/orgs/$orgSlug/apps/$id/deployments'
      path: '/deployments'
      fullPath: '/orgs/$orgSlug/apps/$id/deployments'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdDeploymentsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/settings/': {
      id: '/_authed/orgs/$orgSlug/apps/$id/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/apps/$id/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/settings/webhooks': {
      id: '/_authed/orgs/$orgSlug/apps/$id/settings/webhooks'
      path: '/webhooks'
      fullPath: '/orgs/$orgSlug/apps/$id/settings/webhooks'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsWebhooksRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/settings/protection': {
      id: '/_authed/orgs/$orgSlug/apps/$id/settings/protection'
      path: '/protection'
      fullPath: '/orgs/$orgSlug/apps/$id/settings/protection'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsProtectionRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRoute
    }
    '/_authed/orgs/$orgSlug/apps/$id/settings/advanced': {
      id: '/_authed/orgs/$orgSlug/apps/$id/settings/advanced'
      path: '/advanced'
      fullPath: '/orgs/$orgSlug/apps/$id/settings/advanced'
      preLoaderRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsAdvancedRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRoute
    }
  }
}

interface AuthedOrgsOrgSlugSettingsRouteChildren {
  AuthedOrgsOrgSlugSettingsBillingRoute: typeof AuthedOrgsOrgSlugSettingsBillingRoute
  AuthedOrgsOrgSlugSettingsSsoRoute: typeof AuthedOrgsOrgSlugSettingsSsoRoute
  AuthedOrgsOrgSlugSettingsIndexRoute: typeof AuthedOrgsOrgSlugSettingsIndexRoute
}

const AuthedOrgsOrgSlugSettingsRouteChildren: AuthedOrgsOrgSlugSettingsRouteChildren =
  {
    AuthedOrgsOrgSlugSettingsBillingRoute:
      AuthedOrgsOrgSlugSettingsBillingRoute,
    AuthedOrgsOrgSlugSettingsSsoRoute: AuthedOrgsOrgSlugSettingsSsoRoute,
    AuthedOrgsOrgSlugSettingsIndexRoute: AuthedOrgsOrgSlugSettingsIndexRoute,
  }

const AuthedOrgsOrgSlugSettingsRouteWithChildren =
  AuthedOrgsOrgSlugSettingsRoute._addFileChildren(
    AuthedOrgsOrgSlugSettingsRouteChildren,
  )

interface AuthedOrgsOrgSlugAppsIdSettingsRouteChildren {
  AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute
  AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute
  AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute
  AuthedOrgsOrgSlugAppsIdSettingsIndexRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsIndexRoute
}

const AuthedOrgsOrgSlugAppsIdSettingsRouteChildren: AuthedOrgsOrgSlugAppsIdSettingsRouteChildren =
  {
    AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute:
      AuthedOrgsOrgSlugAppsIdSettingsAdvancedRoute,
    AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute:
      AuthedOrgsOrgSlugAppsIdSettingsProtectionRoute,
    AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute:
      AuthedOrgsOrgSlugAppsIdSettingsWebhooksRoute,
    AuthedOrgsOrgSlugAppsIdSettingsIndexRoute:
      AuthedOrgsOrgSlugAppsIdSettingsIndexRoute,
  }

const AuthedOrgsOrgSlugAppsIdSettingsRouteWithChildren =
  AuthedOrgsOrgSlugAppsIdSettingsRoute._addFileChildren(
    AuthedOrgsOrgSlugAppsIdSettingsRouteChildren,
  )

interface AuthedOrgsOrgSlugAppsIdRouteChildren {
  AuthedOrgsOrgSlugAppsIdDeploymentsRoute: typeof AuthedOrgsOrgSlugAppsIdDeploymentsRoute
  AuthedOrgsOrgSlugAppsIdDomainsRoute: typeof AuthedOrgsOrgSlugAppsIdDomainsRoute
  AuthedOrgsOrgSlugAppsIdEnvRoute: typeof AuthedOrgsOrgSlugAppsIdEnvRoute
  AuthedOrgsOrgSlugAppsIdLogsRoute: typeof AuthedOrgsOrgSlugAppsIdLogsRoute
  AuthedOrgsOrgSlugAppsIdOverviewRoute: typeof AuthedOrgsOrgSlugAppsIdOverviewRoute
  AuthedOrgsOrgSlugAppsIdSettingsRoute: typeof AuthedOrgsOrgSlugAppsIdSettingsRouteWithChildren
  AuthedOrgsOrgSlugAppsIdShellRoute: typeof AuthedOrgsOrgSlugAppsIdShellRoute
  AuthedOrgsOrgSlugAppsIdIndexRoute: typeof AuthedOrgsOrgSlugAppsIdIndexRoute
}

const AuthedOrgsOrgSlugAppsIdRouteChildren: AuthedOrgsOrgSlugAppsIdRouteChildren =
  {
    AuthedOrgsOrgSlugAppsIdDeploymentsRoute:
      AuthedOrgsOrgSlugAppsIdDeploymentsRoute,
    AuthedOrgsOrgSlugAppsIdDomainsRoute: AuthedOrgsOrgSlugAppsIdDomainsRoute,
    AuthedOrgsOrgSlugAppsIdEnvRoute: AuthedOrgsOrgSlugAppsIdEnvRoute,
    AuthedOrgsOrgSlugAppsIdLogsRoute: AuthedOrgsOrgSlugAppsIdLogsRoute,
    AuthedOrgsOrgSlugAppsIdOverviewRoute: AuthedOrgsOrgSlugAppsIdOverviewRoute,
    AuthedOrgsOrgSlugAppsIdSettingsRoute:
      AuthedOrgsOrgSlugAppsIdSettingsRouteWithChildren,
    AuthedOrgsOrgSlugAppsIdShellRoute: AuthedOrgsOrgSlugAppsIdShellRoute,
    AuthedOrgsOrgSlugAppsIdIndexRoute: AuthedOrgsOrgSlugAppsIdIndexRoute,
  }

const AuthedOrgsOrgSlugAppsIdRouteWithChildren =
  AuthedOrgsOrgSlugAppsIdRoute._addFileChildren(
    AuthedOrgsOrgSlugAppsIdRouteChildren,
  )

interface AuthedOrgsOrgSlugRouteChildren {
  AuthedOrgsOrgSlugAuditRoute: typeof AuthedOrgsOrgSlugAuditRoute
  AuthedOrgsOrgSlugBrandingRoute: typeof AuthedOrgsOrgSlugBrandingRoute
  AuthedOrgsOrgSlugDashboardRoute: typeof AuthedOrgsOrgSlugDashboardRoute
  AuthedOrgsOrgSlugMarketplaceRoute: typeof AuthedOrgsOrgSlugMarketplaceRoute
  AuthedOrgsOrgSlugMembersRoute: typeof AuthedOrgsOrgSlugMembersRoute
  AuthedOrgsOrgSlugSettingsRoute: typeof AuthedOrgsOrgSlugSettingsRouteWithChildren
  AuthedOrgsOrgSlugIndexRoute: typeof AuthedOrgsOrgSlugIndexRoute
  AuthedOrgsOrgSlugAppsIdRoute: typeof AuthedOrgsOrgSlugAppsIdRouteWithChildren
  AuthedOrgsOrgSlugDatabasesIdRoute: typeof AuthedOrgsOrgSlugDatabasesIdRoute
  AuthedOrgsOrgSlugServicesIdRoute: typeof AuthedOrgsOrgSlugServicesIdRoute
  AuthedOrgsOrgSlugAppsIndexRoute: typeof AuthedOrgsOrgSlugAppsIndexRoute
  AuthedOrgsOrgSlugDatabasesIndexRoute: typeof AuthedOrgsOrgSlugDatabasesIndexRoute
  AuthedOrgsOrgSlugServicesIndexRoute: typeof AuthedOrgsOrgSlugServicesIndexRoute
}

const AuthedOrgsOrgSlugRouteChildren: AuthedOrgsOrgSlugRouteChildren = {
  AuthedOrgsOrgSlugAuditRoute: AuthedOrgsOrgSlugAuditRoute,
  AuthedOrgsOrgSlugBrandingRoute: AuthedOrgsOrgSlugBrandingRoute,
  AuthedOrgsOrgSlugDashboardRoute: AuthedOrgsOrgSlugDashboardRoute,
  AuthedOrgsOrgSlugMarketplaceRoute: AuthedOrgsOrgSlugMarketplaceRoute,
  AuthedOrgsOrgSlugMembersRoute: AuthedOrgsOrgSlugMembersRoute,
  AuthedOrgsOrgSlugSettingsRoute: AuthedOrgsOrgSlugSettingsRouteWithChildren,
  AuthedOrgsOrgSlugIndexRoute: AuthedOrgsOrgSlugIndexRoute,
  AuthedOrgsOrgSlugAppsIdRoute: AuthedOrgsOrgSlugAppsIdRouteWithChildren,
  AuthedOrgsOrgSlugDatabasesIdRoute: AuthedOrgsOrgSlugDatabasesIdRoute,
  AuthedOrgsOrgSlugServicesIdRoute: AuthedOrgsOrgSlugServicesIdRoute,
  AuthedOrgsOrgSlugAppsIndexRoute: AuthedOrgsOrgSlugAppsIndexRoute,
  AuthedOrgsOrgSlugDatabasesIndexRoute: AuthedOrgsOrgSlugDatabasesIndexRoute,
  AuthedOrgsOrgSlugServicesIndexRoute: AuthedOrgsOrgSlugServicesIndexRoute,
}

const AuthedOrgsOrgSlugRouteWithChildren =
  AuthedOrgsOrgSlugRoute._addFileChildren(AuthedOrgsOrgSlugRouteChildren)

interface AuthedSettingsSecurityRouteChildren {
  AuthedSettingsSecurityPasskeyRoute: typeof AuthedSettingsSecurityPasskeyRoute
  AuthedSettingsSecurityPasskeysRoute: typeof AuthedSettingsSecurityPasskeysRoute
  AuthedSettingsSecurityPostureRoute: typeof AuthedSettingsSecurityPostureRoute
  AuthedSettingsSecuritySessionsRoute: typeof AuthedSettingsSecuritySessionsRoute
  AuthedSettingsSecurityTotpRoute: typeof AuthedSettingsSecurityTotpRoute
  AuthedSettingsSecurityIndexRoute: typeof AuthedSettingsSecurityIndexRoute
}

const AuthedSettingsSecurityRouteChildren: AuthedSettingsSecurityRouteChildren =
  {
    AuthedSettingsSecurityPasskeyRoute: AuthedSettingsSecurityPasskeyRoute,
    AuthedSettingsSecurityPasskeysRoute: AuthedSettingsSecurityPasskeysRoute,
    AuthedSettingsSecurityPostureRoute: AuthedSettingsSecurityPostureRoute,
    AuthedSettingsSecuritySessionsRoute: AuthedSettingsSecuritySessionsRoute,
    AuthedSettingsSecurityTotpRoute: AuthedSettingsSecurityTotpRoute,
    AuthedSettingsSecurityIndexRoute: AuthedSettingsSecurityIndexRoute,
  }

const AuthedSettingsSecurityRouteWithChildren =
  AuthedSettingsSecurityRoute._addFileChildren(
    AuthedSettingsSecurityRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedGuideRoute: typeof AuthedGuideRoute
  AuthedMonitoringRoute: typeof AuthedMonitoringRoute
  AuthedAppsSplatRoute: typeof AuthedAppsSplatRoute
  AuthedDatabasesSplatRoute: typeof AuthedDatabasesSplatRoute
  AuthedOrgsOrgSlugRoute: typeof AuthedOrgsOrgSlugRouteWithChildren
  AuthedSettingsLicenseRoute: typeof AuthedSettingsLicenseRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsRegistryRoute: typeof AuthedSettingsRegistryRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRouteWithChildren
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsGitProvidersSlugRoute: typeof AuthedSettingsGitProvidersSlugRoute
  AuthedSettingsGitProvidersIndexRoute: typeof AuthedSettingsGitProvidersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedGuideRoute: AuthedGuideRoute,
  AuthedMonitoringRoute: AuthedMonitoringRoute,
  AuthedAppsSplatRoute: AuthedAppsSplatRoute,
  AuthedDatabasesSplatRoute: AuthedDatabasesSplatRoute,
  AuthedOrgsOrgSlugRoute: AuthedOrgsOrgSlugRouteWithChildren,
  AuthedSettingsLicenseRoute: AuthedSettingsLicenseRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsRegistryRoute: AuthedSettingsRegistryRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRouteWithChildren,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsGitProvidersSlugRoute: AuthedSettingsGitProvidersSlugRoute,
  AuthedSettingsGitProvidersIndexRoute: AuthedSettingsGitProvidersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInvitationsAcceptRoute: typeof PublicInvitationsAcceptRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInvitationsAcceptRoute: PublicInvitationsAcceptRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
