-- Superseded by 0008_whole_ma_gnuci.
-- This migration is intentionally kept as a no-op because it is referenced by
-- the Drizzle journal. 0008 contains the deploy hook and password rotation
-- schema changes, so applying both on a fresh database must not duplicate
-- tables or columns.
