// SPDX-License-Identifier: AGPL-3.0-only
//
// Exposes the generated Protobuf / tonic stubs for the ploydok.agent.v1 package.
// Re-run `cargo build -p ploydok-proto` after modifying agent.proto to regenerate.

pub mod agent {
    // The include_proto! macro embeds the Rust code generated by tonic-build at
    // build time (stored in OUT_DIR).  The string argument must match the
    // proto `package` declaration: "ploydok.agent.v1".
    tonic::include_proto!("ploydok.agent.v1");
}

// Re-export pour usage direct dans crates downstream (ex: host_stats.rs).
pub use agent::{HostStatsRequest, HostStatsResponse};
